import { JoinContextProvider } from "@/context";
import "./globals.css";
import AOSWrapper from "@/components/AOS Wrapper/Aos";
import { PlanProfileContextProvider } from "@/context/PlanProfileContext";

export const metadata = {
  title: "Orisuun",
  description: "Generated by Next.js",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className="flex flex-col min-h-screen">
        <AOSWrapper>
          <JoinContextProvider>
            <PlanProfileContextProvider>
              <main className="max-w-[1400px] w-full mx-auto ">{children}</main>
            </PlanProfileContextProvider>
          </JoinContextProvider>
        </AOSWrapper>
      </body>
    </html>
  );
}
